# Generated by Django 2.2.6 on 2019-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191018_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicoe',
            name='receita',
            field=models.TextField(default='200 g de arroz'),
        ),
    ]
