# Generated by Django 2.2.6 on 2019-10-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_refeicoe_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoe',
            name='receita',
        ),
    ]
