# Generated by Django 2.2.6 on 2019-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_refeicoe_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='descricao',
            field=models.TextField(default='Pão barrado com queijo de cabra'),
        ),
        migrations.AlterField(
            model_name='refeicoe',
            name='prato',
            field=models.TextField(default='Puré de ganso'),
        ),
    ]
